#!/usr/bin/env python3
# SPDX-License-Identifier: GPL-2.0-or-later
# Copyright DroidVM contributors
# Additional permissions apply; see ADDITIONAL-PERMISSIONS in the repository root.
"""Fail if the guest encoder can send a pNext struct this host decoder cannot take.

The two sides of the cereal codegen are generated separately -- the guest encoder in mesa from
mesa's vk.xml, the host tables here from gfxstream's -- so the guest's struct set can drift
ahead of the host's. When it does, the host's reservedunmarshal_extension_struct() falls into
its default case, reads the wrong number of bytes, and abort()s the VMM. Nothing catches that
before a guest happens to chain the struct, which is why this check exists.

  ./scripts/check-cereal-compat.py [--mesa <mesa checkout>] [--host <gfxstream checkout>]

Anything it reports means the host tree needs a newer gfxstream (or, in a pinch, that the guest
has to stop advertising the extension that introduces the struct). At the time of writing it
reports nothing: this host decodes all 212 structs the guest encoder can send.
"""
import argparse, os, re, sys

# Structs the guest encoder can marshal that this host is known not to decode, each with the
# reason it is safe anyway. Empty, and worth keeping empty: an entry here is a Vulkan feature the
# guest cannot use. It is not empty by luck -- the host cereal is generated from a vk.xml new
# enough to cover everything mesa's encoder emits.
ALLOWED = {}


def switch_cases(path, func):
    """The labels of the *outer* switch in the (last) definition of `func`.

    Several of these dispatchers carry a nested `switch (rootType)` inside one of their cases,
    and a label there is not coverage of the struct -- it only picks a variant once the outer
    switch has already matched. Outer labels are the ones indented by exactly eight spaces.
    """
    lines = open(path).read().split("\n")
    start = None
    for i, line in enumerate(lines):
        if re.match(r"^(?:void|size_t|uint32_t) " + func + r"\(", line):
            start = i
    if start is None:
        sys.exit("%s: no definition of %s" % (path, func))
    out = set()
    for line in lines[start:]:
        if line == "}":
            break
        m = re.match(r"^        case (VK_STRUCTURE_TYPE_\w+):", line)
        if m:
            out.add(m.group(1))
    return out


def main():
    here = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    ap = argparse.ArgumentParser()
    ap.add_argument("--host", default=here)
    ap.add_argument("--mesa", default=os.path.join(here, "..", "..", "..", "..", "mesa"))
    args = ap.parse_args()

    guest = os.path.join(args.mesa, "src/gfxstream/guest/vulkan_enc/autogenerated",
                         "goldfish_vk_marshaling_guest.cpp")
    hostdir = os.path.join(args.host, "host/vulkan/cereal/common")
    for p in (guest, hostdir):
        if not os.path.exists(p):
            sys.exit("not found: %s" % p)

    sendable = switch_cases(guest, "marshal_extension_struct")
    tables = {
        "reservedunmarshal": ("goldfish_vk_reserved_marshaling.cpp", "reservedunmarshal_extension_struct"),
        "marshal": ("goldfish_vk_marshaling.cpp", "marshal_extension_struct"),
        "unmarshal": ("goldfish_vk_marshaling.cpp", "unmarshal_extension_struct"),
        "deepcopy": ("goldfish_vk_deepcopy.cpp", "deepcopy_extension_struct"),
        "size": ("goldfish_vk_extension_structs.cpp", "goldfish_vk_extension_struct_size"),
    }

    bad = {}
    for label, (fname, func) in tables.items():
        # A struct the size table does not know is skipped whole by both sides, which is safe;
        # it is the ones with a size but no marshaling that desynchronise the stream.
        if label == "size":
            continue
        for stype in sorted(sendable - switch_cases(os.path.join(hostdir, fname), func)):
            bad.setdefault(stype, []).append(label)

    known = {s: t for s, t in bad.items() if s in ALLOWED}
    unknown = {s: t for s, t in bad.items() if s not in ALLOWED}

    print("guest encoder can send %d pNext structs" % len(sendable))
    for stype, tabs in sorted(known.items()):
        print("  ok (hidden from the guest: %s)  %s [%s]" % (ALLOWED[stype], stype, ",".join(tabs)))
    for stype, tabs in sorted(unknown.items()):
        print("  MISSING  %s   host tables without a case: %s" % (stype, ", ".join(tabs)))
    if unknown:
        print("\n%d struct(s) would abort the VMM. Splice them into the host cereal, or hide the"
              "\nextension that introduces them and list them in ALLOWED here." % len(unknown))
        return 1
    print("host decoder covers everything the guest encoder can send.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
